### ISSUE TITLE
Install stuck in initial phase when in verbose mode (-v)

### ISSUE THREAD

**Issue by aaqaishtyaq** [javanesse/Asus-ROG-GL552JX-Sierra-10.12-Hackintosh#1]
Hackintosh Install on Asus GL 552jx stuck at the screen after initialising macOS install from clover 2.4 
After blank screen various text displayed stuck on various places but maximum time stuck at com.apple.applefscompressiontypedataless

**Comment by javanesse** [comment]
https://www.youtube.com/watch?v=sCnqkZjMLX8&vl=en
hope will help your problem. goodluck @aaqaishtyaq

**Comment by aaqaishtyaq** [comment]
Everything works now but WiFi is not working as well as USB Ethernet.

Can you help me?

**Comment by javanesse** [comment]
glad to hear that.

about your wifi modules.
- if your wifi is atheros AR956x, that should be work with those kexts.
- but if u have intel wifi module, i have no idea yet for that. please do a research by urself.

for an alternative, u can buy a cheap os x compatilbe external wifi module.
