### ISSUE TITLE
Stuck at busy timeout[0] kextd wait(0): 'AppleACPICPU'

### ISSUE THREAD

**Issue by rohitnettrackers** [javanesse/Asus-ROG-GL552JX-Sierra-10.12-Hackintosh#2]
I am getting error : busy timeout[0], (60s) kextd wait(0): 'AppleACPICPU'
and then the loader appears and it gets stuck for hours. 
Mac runs fine in your older post : https://www.tonymacx86.com/threads/guide-asus-rog-gl552jx-el-capitan-clover-uefi.186163/
But when I try new Kext and DSDT's and Clover plist it gets stuck at above given error.

This is what I did:
1. I copied the DSDTs from "DSDT Ready to Use" and pasted them to ACPI>patched directory
2. installed all the kext from "Kexts Ready to Use"
3. pasted the Clover plist file in required location.
Let me know if there is anything new needs to be done as per the latest commit you have made.

**Comment by javanesse** [comment]
yea, this weird problematic
what loader anyway?
if u mean spining rainbow cursor, then try to install from the other USB port.
but maybe this reference link can help you out : https://www.tonymacx86.com/threads/appleacpicpu-timeout-before-reaching-installer.197482/page-2#post-1296515

Everything's works well on Sierra 10.12.5 except 
- Internal Mic ( still doing a research about pin config)
- Cardreader ( will get work soon)
- Nvidia optimus ( never will)

goodluck

**Comment by rohitnettrackers** [comment]
I followed your advice and did some changes on my own, I don't know which one help but. I am listing it here it might help someone:
1. Used Clover Clover r4097. version r4091 was buggy.
2. Created installation usb using clover options :
   *Install Clover in the esp
   *install boot0af in MBR
   *Clover64 bit sata.
3. Copied all kext from /Library/Extension and pasted them on /EFI/CLOVER/kexts/10.12 and others folder along with "Kexts Ready to Use" kext listed on the github.

BTW added 
<key>FixShutdown_0004</key>
<true/>
to prevent shutdown issue.

And everything worked smoothly :)

Thanks Again javanesse you Rock 👍
